services:
    image: registry.cn-beijing.aliyuncs.com/ucse/test
    container_name: test
    # 更友好的自重启
    restart: unless-stopped
    # host
    #hostname: 'git.bch.ucse.net'
    # 环境变量
    #environment:
        #TEST: "test"
    ports:
        #- "80:80"
        #- "443:443"
        - "8080:8181"
    # 映射挂载
    volumes:
        - "/var/www/ucse/:/var/www/"
        #- "/var/log/nginx/:/var/log/nginx/"
    #links:
        #    - php